#!/bin/bash

install_ide() {
    while true; do
        read -p "install neovim? (yn): " RESP
        case $RESP in 
            [Yy]* ) 
                install_neovim
                install_tmux
                break;;
            [Nn]* )
                break;;
            * )
                echo "yes or no"
        esac
    done

    while true; do
        read -p "install vs-code? (yn): " RESP
        case $RESP in 
            [Yy]* ) 
                install_code
                break;;
            [Nn]* )
                break;;
            * )
                echo "yes or no"
        esac
    done
}

install_tmux() {
    sudo mkdir -p /opt/tmux/

    pushd /opt/tmux
    sudo wget https://github.com/nelsonenzo/tmux-appimage/releases/latest/download/tmux.appimage
    sudo chmod +x tmux.appimage
    sudo ln -s /opt/tmux/tmux.appimage /opt/bin/tmux
    popd

    git clone git@github.com:tmux-plugins/tpm.git "$HOME"/.tmux/plugins/tpm
    "$HOME"/.tmux/plugins/tpm/tpm
}

install_neovim() {
    sudo mkdir -p /opt/nvim/

    pushd /opt/nvim 
    case "$OSTYPE" in 
    "linux"*)
        sudo wget https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
        sudo chmod +x nvim.appimage
        sudo ln -s /opt/nvim/nvim.appimage /opt/bin/nvim
        ;;
    "darwin"*)
        local arch="$(uname -m)"
        sudo wget "https://github.com/neovim/neovim/releases/download/nightly/nvim-macos-$arch.tar.gz"
        sudo tar xzf "nvim-macos-$arch.tar.gz"
        sudo chmod +x "nvim-macos-$arch/bin/nvim"
        sudo ln -sf "/opt/nvim/nvim-macos-$arch/bin/nvim" /opt/bin/nvim
        sudo rm -rf "nvim-macos-$arch.tar.gz"
        ;;
    esac
    popd

    git clone https://github.com/NvChad/starter ~/.config/nvim --depth 1
}

install_code() {
    sudo snap install code

    # Install packages
    pkglist=(
        ms-vscode.cpptools
        vscodevim.vim
    )

    for i in ${pkglist[@]}; do
      code --install-extension $i
    done
}
