#!/bin/bash

install_ide() {
    while true; do
        read -p "install neovim? (yn): " RESP
        case $RESP in 
            [Yy]* ) 
                install_neovim
                install_tmux
                break;;
            [Nn]* )
                break;;
            * )
                echo "yes or no"
        esac
    done

    while true; do
        read -p "install vs-code? (yn): " RESP
        case $RESP in 
            [Yy]* ) 
                install_code
                break;;
            [Nn]* )
                break;;
            * )
                echo "yes or no"
        esac
    done
}

install_tmux() {
    sudo mkdir -p /opt/tmux/

    pushd /opt/tmux
    sudo wget https://github.com/nelsonenzo/tmux-appimage/releases/latest/download/tmux.appimage
    sudo chmod +x tmux.appimage
    sudo ln -s /opt/tmux/tmux.appimage /opt/bin/tmux
    popd

    git clone git@github.com:tmux-plugins/tpm.git "$HOME"/.tmux/plugins/tpm
    "$HOME"/.tmux/plugins/tpm/tpm
}

install_neovim() {
    sudo mkdir -p /opt/nvim/

    pushd /opt/nvim 
    sudo wget https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    sudo chmod +x nvim.appimage
    sudo ln -s /opt/nvim/nvim.appimage /opt/bin/nvim
    popd

    git clone git@github.com:NvChad/NvChad.git "$HOME"/.config/nvim
}

install_code() {
    sudo snap install code

    # Install packages
    pkglist=(
        ms-vscode.cpptools
        vscodevim.vim
    )

    for i in ${pkglist[@]}; do
      code --install-extension $i
    done
}

install_ide
