#!/bin/bash

install_dev_packages() {
    ## Install C/C++ dev tools
    while true; do
        read -p "Do you want to install C/C++ dev tools? (yn): " RESP
        case $RESP in 
            [Yy]* ) 
                sudo apt install -y build-essential cmake clang
                break;;
            [Nn]* )
                break;;
            * )
                echo "yes or no"
        esac
    done

    ## Install Rust dev tools
    while true; do
        read -p "Do you want to install Rust dev tools? (yn): " RESP
        case $RESP in 
            [Yy]* ) 
                curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
                rustup toolchain install stable
                break;;
            [Nn]* )
                break;;
            * )
                echo "yes or no"
        esac
    done

    ## Install Flutter dev tools
    while true; do
        read -p "Do you want to install Flutter dev tools? (yn): " RESP
        case $RESP in 
            [Yy]* ) 
                install_flutter
                break;;
            [Nn]* )
                break;;
            * )
                echo "yes or no"
        esac
    done
}

install_flutter() {
    mkdir -p tmp 
    pushd tmp

    # TODO change this to automatically get the latest version
    wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.19.3-stable.tar.xz
    sudo tar -xvf flutter_linux_*-stable.tar.xz -C /opt
    sudo ln -s /opt/flutter/bin/* /opt/bin/
    /opt/bin/flutter doctor

    popd
    rm -rf tmp
}

install_dev_packages
