#!/bin/bash

DISTRO=$(. /etc/os-release && echo "$ID")
VERSION=$(. /etc/os-release && echo "$VERSION_CODENAME")

install_docker() {
    # Remove conflicting packages
    for pkg in docker.io docker-doc docker-compose docker-compose-v2 \
        podman-docker containerd runc; do 
        sudo apt-get remove $pkg; 
    done

    # Add Docker's official GPG key:
    sudo apt-get update
    sudo apt-get install ca-certificates curl
    sudo install -m 0755 -d /etc/apt/keyrings
    sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    sudo chmod a+r /etc/apt/keyrings/docker.asc

    # Add the repository to Apt sources:
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
      https://download.docker.com/linux/"$DISTRO" \
      "$VERSION" stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    sudo apt-get update

    # Install the docker packages
    sudo apt-get install docker-ce docker-ce-cli containerd.io
    
    if [[ "$VERSION" != "eoan" ]]; then
        sudo apt install docker-buildx-plugin docker-compose-plugin
    fi

    # Create non priviliged user group
    sudo groupadd docker
    sudo usermod -aG docker $USER
    
    # Apply the changes
    newgrp docker
}

install_docker
