#!/bin/bash

SCRIPT_PATH=$(dirname "$0")

main() {
    echo 
    echo ===== UPDATING SYSTEM ================================================
    sudo apt update

    echo 
    echo ===== CREATING REQUIRED DIRECTORIES ==================================
    echo "/opt/bin"
    sudo mkdir -p /opt/bin/

    . $SCRIPT_PATH/../dotfiles/.zshenv
    echo "$XDG_CONFIG_HOME"
    mkdir -p "$XDG_CONFIG_HOME"

    echo 
    echo ===== INSTALLING GENERAL PACKAGES ====================================
    "$SCRIPT_PATH"/install/install_general_packages

    echo 
    echo ===== INSTALLING IDE =================================================
    "$SCRIPT_PATH"/install/install_ide

    echo 
    echo ===== INSTALLING DEV DEPENDANCIES ====================================
    "$SCRIPT_PATH"/install/install_dev_packages
    "$SCRIPT_PATH"/install/install_fonts

    echo 
    echo ===== SWITCHING TO ZSH ===============================================
    chsh -s $(which zsh)

    echo 
    echo ===== CREATING SYMBOLIC LINKS ========================================
    DIR=$(git rev-parse --show-toplevel)
    "$SCRIPT_PATH"/create-sym-links.sh
}

main
